### ISSUE TITLE
Wouldn't it be nice if termux touch only was a file in unicurses/demos

### ISSUE THREAD

**Issue by cargilcm** [GiorgosXou/TUIFIManager#114]
**this feature is requested in the tuifimanager repo vs unicurses b/c the former works on mobile(termux). Unicurses demos' test_mousemenu.py does not.**
I would like to build a console app with context-like menus that respond to termux touch input and I can't figure out how tuifimanager implements unicurses as such

**alternatives i've considered**
None, great job with tuifimanager concept, impl. etc!

**Comment by GiorgosXou** [comment]
> This feature is requested in the tuifimanager repo vs unicurses b/c ...

It should had been requested at unicurses but everything's fine don't worry :sweat_smile:

> Unicurses demos'  test_mousemenu.py does not *(work on termux)*.

**Just replace [`BUTTON1_PRESSED`](https://github.com/unicurses/unicurses/blob/master/demos/test_mousemenu.py#L59) with `BUTTON1_CLICKED` and it should work** *(or better include both)*. Now, the reason behind this issue is because termux doesn't register "pressed" or "released" events at all... which means that  `mouseinterval(0)` has no effect for it and therefore it always fires `BUTTON1_CLICKED`. On the other hand, if you try to catch `BUTTON1_CLICKED` with a `mouseinterval(...)` set to `0` ouside of termux, you will realise it's impossible  [...]

> I can't figure out how tuifimanager implements unicurses as such

Here's how tuifi does it *(ignore `BUTTON1_PRESSED`)*:
https://github.com/GiorgosXou/TUIFIManager/blob/bb0bde0d6031348d2d9ab54511ce9817f22f9c0b/TUIFIManager/__init__.py#L1344-L1357

And for scrolling you may use `BUTTON4_PRESSED` and `BUTTON5_PRESSED`
https://github.com/GiorgosXou/TUIFIManager/blob/bb0bde0d6031348d2d9ab54511ce9817f22f9c0b/TUIFIManager/__init__.py#L1384-L1385

> Wouldn't it be nice if termux touch only was a file in unicurses/demos

Yeah... but I have to look into it a bit, because it might not be 

> None, great job with tuifimanager concept, impl. etc!

Thanks 🤗
