### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by hissssst** [GiorgosXou/TUIFIManager#23]
Randomly freezes when using

```
python 3.9
tuifi from pipy 1.3.3
unicurses from pipy 2.1.0
ncurses6 6.3-p20220507
alacritty 0.11.0
```

https://user-images.githubusercontent.com/37012324/206681334-a510456e-a7cd-46a9-8af3-8df7887e416b.mp4

**Comment by GiorgosXou** [comment]
That's really weird, I can only think of two possible reasons why this is happening, at the moment:
1. this might be related to symlinks or
2. related to the translation of some keys, resulting in the execution of the auto searching function. 

 Could you try the below:
* run `python -c 'import TUIFIManager; print(TUIFIManager.__path__)'`
* ^ `cd` into that directory, and add `auto_find_on_typing=true` at the end of this line:
https://github.com/GiorgosXou/TUIFIManager/blob/db2f2f667fc3e2a09680720f9961fcb52630312f/TUIFIManager/__main__.py#L39
* and let me know, if that fixed the issue?

**Comment by GiorgosXou** [comment]
This is really weird, because I have quite the same specs...**What OS, do you use? is it FreeBSD by any chance?** This issue, I'm guessing that it has to do with the unpacking of the real-path:
https://github.com/GiorgosXou/TUIFIManager/blob/db2f2f667fc3e2a09680720f9961fcb52630312f/TUIFIManager/__init__.py#L150

---

So, try this:

- open the `__init__.py`
- go below this line, out of the "for-loop":
https://github.com/GiorgosXou/TUIFIManager/blob/db2f2f667fc3e2a09680720f9961fcb52630312f/TUIFIManager/__init__.py#L129
- add this line: 
`unicurses.mvwaddwstr(self.pad,0,0, self.directory)`

and let me know with a recording, what it showed up
