### ISSUE TITLE
CTRL + S is default for stop processing terminal

### ISSUE THREAD

**Issue by paxsali** [GiorgosXou/TUIFIManager#3]
Just wanted to point out that for a terminal based utility, the default keybinding `CTRL +S` is highly problematic,
as for most environments it means freeze / don't update / stop scrolling the terminal.
(with `CTRL + Q` meaning continue / unfreeze / resume scrolling).

Please consider to replace this default binding with something less irritating to most users.

Thanks.

**Comment by GiorgosXou** [comment]
Thanks, I didn't know that, maybe If there's a `signal` I will be able to override it just like I *(kind of)* did with `ctrl+c` too. Although this keyblinding  is supposed to be exclusive to the touch behavior of termux and that's because I wasn't able to find any long press\touch or whatever other event for it [...]

**Comment by GiorgosXou** [comment]
[v.1.1.3](https://github.com/GiorgosXou/TUIFIManager/blob/master/CHANGELOG.md)
